# credits to https://docs.docker.com/guides/dex/
services:
  dex:
    image: dexidp/dex:latest
    container_name: dex
    ports:
      - "5556:5556"
    volumes:
      - ./dex.config.yml:/etc/dex/config.yaml
    command: [ "dex", "serve", "/etc/dex/config.yaml" ]