/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RpcStatus,
} from '../models/index';
import {
    RpcStatusFromJSON,
    RpcStatusToJSON,
} from '../models/index';

export interface HealthServiceHealthCheckRequest {
    body: object;
}

/**
 * 
 */
export class HealthServiceApi extends runtime.BaseAPI {

    /**
     */
    async healthServiceHealthCheckRaw(requestParameters: HealthServiceHealthCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling healthServiceHealthCheck().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/dig_inv.HealthService/HealthCheck`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async healthServiceHealthCheck(requestParameters: HealthServiceHealthCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.healthServiceHealthCheckRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
