/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DigInvElementId,
  DigInvUserGroup,
  RpcStatus,
} from '../models/index';
import {
    DigInvElementIdFromJSON,
    DigInvElementIdToJSON,
    DigInvUserGroupFromJSON,
    DigInvUserGroupToJSON,
    RpcStatusFromJSON,
    RpcStatusToJSON,
} from '../models/index';

export interface UserGroupServiceAddItemToGroupRequest {
    body: DigInvElementId;
}

export interface UserGroupServiceCreateGroupRequest {
    body: DigInvUserGroup;
}

export interface UserGroupServiceDeleteGroupRequest {
    body: DigInvElementId;
}

export interface UserGroupServiceGetGroupRequest {
    body: object;
}

export interface UserGroupServiceGetGroupsRequest {
    body: object;
}

export interface UserGroupServiceUpdateGroupRequest {
    body: DigInvUserGroup;
}

/**
 * 
 */
export class UserGroupServiceApi extends runtime.BaseAPI {

    /**
     */
    async userGroupServiceAddItemToGroupRaw(requestParameters: UserGroupServiceAddItemToGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling userGroupServiceAddItemToGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/dig_inv.UserGroupService/AddItemToGroup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DigInvElementIdToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async userGroupServiceAddItemToGroup(requestParameters: UserGroupServiceAddItemToGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.userGroupServiceAddItemToGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async userGroupServiceCreateGroupRaw(requestParameters: UserGroupServiceCreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DigInvUserGroup>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling userGroupServiceCreateGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/dig_inv.UserGroupService/CreateGroup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DigInvUserGroupToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DigInvUserGroupFromJSON(jsonValue));
    }

    /**
     */
    async userGroupServiceCreateGroup(requestParameters: UserGroupServiceCreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DigInvUserGroup> {
        const response = await this.userGroupServiceCreateGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async userGroupServiceDeleteGroupRaw(requestParameters: UserGroupServiceDeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling userGroupServiceDeleteGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/dig_inv.UserGroupService/DeleteGroup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DigInvElementIdToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async userGroupServiceDeleteGroup(requestParameters: UserGroupServiceDeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.userGroupServiceDeleteGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async userGroupServiceGetGroupRaw(requestParameters: UserGroupServiceGetGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DigInvUserGroup>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling userGroupServiceGetGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/dig_inv.UserGroupService/GetGroup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DigInvUserGroupFromJSON(jsonValue));
    }

    /**
     */
    async userGroupServiceGetGroup(requestParameters: UserGroupServiceGetGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DigInvUserGroup> {
        const response = await this.userGroupServiceGetGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async userGroupServiceGetGroupsRaw(requestParameters: UserGroupServiceGetGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DigInvUserGroup>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling userGroupServiceGetGroups().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/dig_inv.UserGroupService/GetGroups`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DigInvUserGroupFromJSON(jsonValue));
    }

    /**
     */
    async userGroupServiceGetGroups(requestParameters: UserGroupServiceGetGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DigInvUserGroup> {
        const response = await this.userGroupServiceGetGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async userGroupServiceUpdateGroupRaw(requestParameters: UserGroupServiceUpdateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DigInvUserGroup>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling userGroupServiceUpdateGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/dig_inv.UserGroupService/UpdateGroup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DigInvUserGroupToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DigInvUserGroupFromJSON(jsonValue));
    }

    /**
     */
    async userGroupServiceUpdateGroup(requestParameters: UserGroupServiceUpdateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DigInvUserGroup> {
        const response = await this.userGroupServiceUpdateGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
