// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"dig-inv/ent/assetclass"
	"dig-inv/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AssetClassQuery is the builder for querying AssetClass entities.
type AssetClassQuery struct {
	config
	ctx        *QueryContext
	order      []assetclass.OrderOption
	inters     []Interceptor
	predicates []predicate.AssetClass
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AssetClassQuery builder.
func (acq *AssetClassQuery) Where(ps ...predicate.AssetClass) *AssetClassQuery {
	acq.predicates = append(acq.predicates, ps...)
	return acq
}

// Limit the number of records to be returned by this query.
func (acq *AssetClassQuery) Limit(limit int) *AssetClassQuery {
	acq.ctx.Limit = &limit
	return acq
}

// Offset to start from.
func (acq *AssetClassQuery) Offset(offset int) *AssetClassQuery {
	acq.ctx.Offset = &offset
	return acq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (acq *AssetClassQuery) Unique(unique bool) *AssetClassQuery {
	acq.ctx.Unique = &unique
	return acq
}

// Order specifies how the records should be ordered.
func (acq *AssetClassQuery) Order(o ...assetclass.OrderOption) *AssetClassQuery {
	acq.order = append(acq.order, o...)
	return acq
}

// First returns the first AssetClass entity from the query.
// Returns a *NotFoundError when no AssetClass was found.
func (acq *AssetClassQuery) First(ctx context.Context) (*AssetClass, error) {
	nodes, err := acq.Limit(1).All(setContextOp(ctx, acq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{assetclass.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (acq *AssetClassQuery) FirstX(ctx context.Context) *AssetClass {
	node, err := acq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AssetClass ID from the query.
// Returns a *NotFoundError when no AssetClass ID was found.
func (acq *AssetClassQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = acq.Limit(1).IDs(setContextOp(ctx, acq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{assetclass.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (acq *AssetClassQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := acq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AssetClass entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AssetClass entity is found.
// Returns a *NotFoundError when no AssetClass entities are found.
func (acq *AssetClassQuery) Only(ctx context.Context) (*AssetClass, error) {
	nodes, err := acq.Limit(2).All(setContextOp(ctx, acq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{assetclass.Label}
	default:
		return nil, &NotSingularError{assetclass.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (acq *AssetClassQuery) OnlyX(ctx context.Context) *AssetClass {
	node, err := acq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AssetClass ID in the query.
// Returns a *NotSingularError when more than one AssetClass ID is found.
// Returns a *NotFoundError when no entities are found.
func (acq *AssetClassQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = acq.Limit(2).IDs(setContextOp(ctx, acq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{assetclass.Label}
	default:
		err = &NotSingularError{assetclass.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (acq *AssetClassQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := acq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AssetClasses.
func (acq *AssetClassQuery) All(ctx context.Context) ([]*AssetClass, error) {
	ctx = setContextOp(ctx, acq.ctx, ent.OpQueryAll)
	if err := acq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AssetClass, *AssetClassQuery]()
	return withInterceptors[[]*AssetClass](ctx, acq, qr, acq.inters)
}

// AllX is like All, but panics if an error occurs.
func (acq *AssetClassQuery) AllX(ctx context.Context) []*AssetClass {
	nodes, err := acq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AssetClass IDs.
func (acq *AssetClassQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if acq.ctx.Unique == nil && acq.path != nil {
		acq.Unique(true)
	}
	ctx = setContextOp(ctx, acq.ctx, ent.OpQueryIDs)
	if err = acq.Select(assetclass.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (acq *AssetClassQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := acq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (acq *AssetClassQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, acq.ctx, ent.OpQueryCount)
	if err := acq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, acq, querierCount[*AssetClassQuery](), acq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (acq *AssetClassQuery) CountX(ctx context.Context) int {
	count, err := acq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (acq *AssetClassQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, acq.ctx, ent.OpQueryExist)
	switch _, err := acq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (acq *AssetClassQuery) ExistX(ctx context.Context) bool {
	exist, err := acq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AssetClassQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (acq *AssetClassQuery) Clone() *AssetClassQuery {
	if acq == nil {
		return nil
	}
	return &AssetClassQuery{
		config:     acq.config,
		ctx:        acq.ctx.Clone(),
		order:      append([]assetclass.OrderOption{}, acq.order...),
		inters:     append([]Interceptor{}, acq.inters...),
		predicates: append([]predicate.AssetClass{}, acq.predicates...),
		// clone intermediate query.
		sql:  acq.sql.Clone(),
		path: acq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Order int `json:"order,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AssetClass.Query().
//		GroupBy(assetclass.FieldOrder).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (acq *AssetClassQuery) GroupBy(field string, fields ...string) *AssetClassGroupBy {
	acq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AssetClassGroupBy{build: acq}
	grbuild.flds = &acq.ctx.Fields
	grbuild.label = assetclass.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Order int `json:"order,omitempty"`
//	}
//
//	client.AssetClass.Query().
//		Select(assetclass.FieldOrder).
//		Scan(ctx, &v)
func (acq *AssetClassQuery) Select(fields ...string) *AssetClassSelect {
	acq.ctx.Fields = append(acq.ctx.Fields, fields...)
	sbuild := &AssetClassSelect{AssetClassQuery: acq}
	sbuild.label = assetclass.Label
	sbuild.flds, sbuild.scan = &acq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AssetClassSelect configured with the given aggregations.
func (acq *AssetClassQuery) Aggregate(fns ...AggregateFunc) *AssetClassSelect {
	return acq.Select().Aggregate(fns...)
}

func (acq *AssetClassQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range acq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, acq); err != nil {
				return err
			}
		}
	}
	for _, f := range acq.ctx.Fields {
		if !assetclass.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if acq.path != nil {
		prev, err := acq.path(ctx)
		if err != nil {
			return err
		}
		acq.sql = prev
	}
	return nil
}

func (acq *AssetClassQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AssetClass, error) {
	var (
		nodes   = []*AssetClass{}
		withFKs = acq.withFKs
		_spec   = acq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, assetclass.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AssetClass).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AssetClass{config: acq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, acq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (acq *AssetClassQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := acq.querySpec()
	_spec.Node.Columns = acq.ctx.Fields
	if len(acq.ctx.Fields) > 0 {
		_spec.Unique = acq.ctx.Unique != nil && *acq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, acq.driver, _spec)
}

func (acq *AssetClassQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(assetclass.Table, assetclass.Columns, sqlgraph.NewFieldSpec(assetclass.FieldID, field.TypeUUID))
	_spec.From = acq.sql
	if unique := acq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if acq.path != nil {
		_spec.Unique = true
	}
	if fields := acq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assetclass.FieldID)
		for i := range fields {
			if fields[i] != assetclass.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := acq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := acq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := acq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := acq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (acq *AssetClassQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(acq.driver.Dialect())
	t1 := builder.Table(assetclass.Table)
	columns := acq.ctx.Fields
	if len(columns) == 0 {
		columns = assetclass.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if acq.sql != nil {
		selector = acq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if acq.ctx.Unique != nil && *acq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range acq.predicates {
		p(selector)
	}
	for _, p := range acq.order {
		p(selector)
	}
	if offset := acq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := acq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AssetClassGroupBy is the group-by builder for AssetClass entities.
type AssetClassGroupBy struct {
	selector
	build *AssetClassQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (acgb *AssetClassGroupBy) Aggregate(fns ...AggregateFunc) *AssetClassGroupBy {
	acgb.fns = append(acgb.fns, fns...)
	return acgb
}

// Scan applies the selector query and scans the result into the given value.
func (acgb *AssetClassGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, acgb.build.ctx, ent.OpQueryGroupBy)
	if err := acgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssetClassQuery, *AssetClassGroupBy](ctx, acgb.build, acgb, acgb.build.inters, v)
}

func (acgb *AssetClassGroupBy) sqlScan(ctx context.Context, root *AssetClassQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(acgb.fns))
	for _, fn := range acgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*acgb.flds)+len(acgb.fns))
		for _, f := range *acgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*acgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := acgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AssetClassSelect is the builder for selecting fields of AssetClass entities.
type AssetClassSelect struct {
	*AssetClassQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (acs *AssetClassSelect) Aggregate(fns ...AggregateFunc) *AssetClassSelect {
	acs.fns = append(acs.fns, fns...)
	return acs
}

// Scan applies the selector query and scans the result into the given value.
func (acs *AssetClassSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, acs.ctx, ent.OpQuerySelect)
	if err := acs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssetClassQuery, *AssetClassSelect](ctx, acs.AssetClassQuery, acs, acs.inters, v)
}

func (acs *AssetClassSelect) sqlScan(ctx context.Context, root *AssetClassQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(acs.fns))
	for _, fn := range acs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*acs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := acs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
