// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"dig-inv/ent/assetclass"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AssetClassCreate is the builder for creating a AssetClass entity.
type AssetClassCreate struct {
	config
	mutation *AssetClassMutation
	hooks    []Hook
}

// SetOrder sets the "order" field.
func (acc *AssetClassCreate) SetOrder(i int) *AssetClassCreate {
	acc.mutation.SetOrder(i)
	return acc
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (acc *AssetClassCreate) SetNillableOrder(i *int) *AssetClassCreate {
	if i != nil {
		acc.SetOrder(*i)
	}
	return acc
}

// SetName sets the "name" field.
func (acc *AssetClassCreate) SetName(s string) *AssetClassCreate {
	acc.mutation.SetName(s)
	return acc
}

// SetDescription sets the "description" field.
func (acc *AssetClassCreate) SetDescription(s string) *AssetClassCreate {
	acc.mutation.SetDescription(s)
	return acc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (acc *AssetClassCreate) SetNillableDescription(s *string) *AssetClassCreate {
	if s != nil {
		acc.SetDescription(*s)
	}
	return acc
}

// SetIcon sets the "icon" field.
func (acc *AssetClassCreate) SetIcon(s string) *AssetClassCreate {
	acc.mutation.SetIcon(s)
	return acc
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (acc *AssetClassCreate) SetNillableIcon(s *string) *AssetClassCreate {
	if s != nil {
		acc.SetIcon(*s)
	}
	return acc
}

// SetColor sets the "color" field.
func (acc *AssetClassCreate) SetColor(s string) *AssetClassCreate {
	acc.mutation.SetColor(s)
	return acc
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (acc *AssetClassCreate) SetNillableColor(s *string) *AssetClassCreate {
	if s != nil {
		acc.SetColor(*s)
	}
	return acc
}

// SetProvider sets the "provider" field.
func (acc *AssetClassCreate) SetProvider(s string) *AssetClassCreate {
	acc.mutation.SetProvider(s)
	return acc
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (acc *AssetClassCreate) SetNillableProvider(s *string) *AssetClassCreate {
	if s != nil {
		acc.SetProvider(*s)
	}
	return acc
}

// SetCreatedBy sets the "created_by" field.
func (acc *AssetClassCreate) SetCreatedBy(s string) *AssetClassCreate {
	acc.mutation.SetCreatedBy(s)
	return acc
}

// SetCreatedAt sets the "created_at" field.
func (acc *AssetClassCreate) SetCreatedAt(t time.Time) *AssetClassCreate {
	acc.mutation.SetCreatedAt(t)
	return acc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (acc *AssetClassCreate) SetNillableCreatedAt(t *time.Time) *AssetClassCreate {
	if t != nil {
		acc.SetCreatedAt(*t)
	}
	return acc
}

// SetUpdatedBy sets the "updated_by" field.
func (acc *AssetClassCreate) SetUpdatedBy(s string) *AssetClassCreate {
	acc.mutation.SetUpdatedBy(s)
	return acc
}

// SetUpdatedAt sets the "updated_at" field.
func (acc *AssetClassCreate) SetUpdatedAt(t time.Time) *AssetClassCreate {
	acc.mutation.SetUpdatedAt(t)
	return acc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (acc *AssetClassCreate) SetNillableUpdatedAt(t *time.Time) *AssetClassCreate {
	if t != nil {
		acc.SetUpdatedAt(*t)
	}
	return acc
}

// SetDeletedBy sets the "deleted_by" field.
func (acc *AssetClassCreate) SetDeletedBy(s string) *AssetClassCreate {
	acc.mutation.SetDeletedBy(s)
	return acc
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (acc *AssetClassCreate) SetNillableDeletedBy(s *string) *AssetClassCreate {
	if s != nil {
		acc.SetDeletedBy(*s)
	}
	return acc
}

// SetDeletedAt sets the "deleted_at" field.
func (acc *AssetClassCreate) SetDeletedAt(t time.Time) *AssetClassCreate {
	acc.mutation.SetDeletedAt(t)
	return acc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (acc *AssetClassCreate) SetNillableDeletedAt(t *time.Time) *AssetClassCreate {
	if t != nil {
		acc.SetDeletedAt(*t)
	}
	return acc
}

// SetID sets the "id" field.
func (acc *AssetClassCreate) SetID(u uuid.UUID) *AssetClassCreate {
	acc.mutation.SetID(u)
	return acc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (acc *AssetClassCreate) SetNillableID(u *uuid.UUID) *AssetClassCreate {
	if u != nil {
		acc.SetID(*u)
	}
	return acc
}

// Mutation returns the AssetClassMutation object of the builder.
func (acc *AssetClassCreate) Mutation() *AssetClassMutation {
	return acc.mutation
}

// Save creates the AssetClass in the database.
func (acc *AssetClassCreate) Save(ctx context.Context) (*AssetClass, error) {
	acc.defaults()
	return withHooks(ctx, acc.sqlSave, acc.mutation, acc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (acc *AssetClassCreate) SaveX(ctx context.Context) *AssetClass {
	v, err := acc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acc *AssetClassCreate) Exec(ctx context.Context) error {
	_, err := acc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acc *AssetClassCreate) ExecX(ctx context.Context) {
	if err := acc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (acc *AssetClassCreate) defaults() {
	if _, ok := acc.mutation.Order(); !ok {
		v := assetclass.DefaultOrder
		acc.mutation.SetOrder(v)
	}
	if _, ok := acc.mutation.CreatedAt(); !ok {
		v := assetclass.DefaultCreatedAt()
		acc.mutation.SetCreatedAt(v)
	}
	if _, ok := acc.mutation.UpdatedAt(); !ok {
		v := assetclass.DefaultUpdatedAt()
		acc.mutation.SetUpdatedAt(v)
	}
	if _, ok := acc.mutation.ID(); !ok {
		v := assetclass.DefaultID()
		acc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (acc *AssetClassCreate) check() error {
	if _, ok := acc.mutation.Order(); !ok {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required field "AssetClass.order"`)}
	}
	if _, ok := acc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AssetClass.name"`)}
	}
	if v, ok := acc.mutation.Name(); ok {
		if err := assetclass.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AssetClass.name": %w`, err)}
		}
	}
	if _, ok := acc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "AssetClass.created_by"`)}
	}
	if _, ok := acc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AssetClass.created_at"`)}
	}
	if _, ok := acc.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "AssetClass.updated_by"`)}
	}
	if _, ok := acc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AssetClass.updated_at"`)}
	}
	return nil
}

func (acc *AssetClassCreate) sqlSave(ctx context.Context) (*AssetClass, error) {
	if err := acc.check(); err != nil {
		return nil, err
	}
	_node, _spec := acc.createSpec()
	if err := sqlgraph.CreateNode(ctx, acc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	acc.mutation.id = &_node.ID
	acc.mutation.done = true
	return _node, nil
}

func (acc *AssetClassCreate) createSpec() (*AssetClass, *sqlgraph.CreateSpec) {
	var (
		_node = &AssetClass{config: acc.config}
		_spec = sqlgraph.NewCreateSpec(assetclass.Table, sqlgraph.NewFieldSpec(assetclass.FieldID, field.TypeUUID))
	)
	if id, ok := acc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := acc.mutation.Order(); ok {
		_spec.SetField(assetclass.FieldOrder, field.TypeInt, value)
		_node.Order = value
	}
	if value, ok := acc.mutation.Name(); ok {
		_spec.SetField(assetclass.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := acc.mutation.Description(); ok {
		_spec.SetField(assetclass.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := acc.mutation.Icon(); ok {
		_spec.SetField(assetclass.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := acc.mutation.Color(); ok {
		_spec.SetField(assetclass.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if value, ok := acc.mutation.Provider(); ok {
		_spec.SetField(assetclass.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := acc.mutation.CreatedBy(); ok {
		_spec.SetField(assetclass.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := acc.mutation.CreatedAt(); ok {
		_spec.SetField(assetclass.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := acc.mutation.UpdatedBy(); ok {
		_spec.SetField(assetclass.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := acc.mutation.UpdatedAt(); ok {
		_spec.SetField(assetclass.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := acc.mutation.DeletedBy(); ok {
		_spec.SetField(assetclass.FieldDeletedBy, field.TypeString, value)
		_node.DeletedBy = value
	}
	if value, ok := acc.mutation.DeletedAt(); ok {
		_spec.SetField(assetclass.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	return _node, _spec
}

// AssetClassCreateBulk is the builder for creating many AssetClass entities in bulk.
type AssetClassCreateBulk struct {
	config
	err      error
	builders []*AssetClassCreate
}

// Save creates the AssetClass entities in the database.
func (accb *AssetClassCreateBulk) Save(ctx context.Context) ([]*AssetClass, error) {
	if accb.err != nil {
		return nil, accb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(accb.builders))
	nodes := make([]*AssetClass, len(accb.builders))
	mutators := make([]Mutator, len(accb.builders))
	for i := range accb.builders {
		func(i int, root context.Context) {
			builder := accb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetClassMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, accb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, accb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, accb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (accb *AssetClassCreateBulk) SaveX(ctx context.Context) []*AssetClass {
	v, err := accb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (accb *AssetClassCreateBulk) Exec(ctx context.Context) error {
	_, err := accb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (accb *AssetClassCreateBulk) ExecX(ctx context.Context) {
	if err := accb.Exec(ctx); err != nil {
		panic(err)
	}
}
