// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"dig-inv/ent/item"
	"dig-inv/ent/predicate"
	"dig-inv/ent/usergroup"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserGroupUpdate is the builder for updating UserGroup entities.
type UserGroupUpdate struct {
	config
	hooks    []Hook
	mutation *UserGroupMutation
}

// Where appends a list predicates to the UserGroupUpdate builder.
func (ugu *UserGroupUpdate) Where(ps ...predicate.UserGroup) *UserGroupUpdate {
	ugu.mutation.Where(ps...)
	return ugu
}

// SetName sets the "name" field.
func (ugu *UserGroupUpdate) SetName(s string) *UserGroupUpdate {
	ugu.mutation.SetName(s)
	return ugu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableName(s *string) *UserGroupUpdate {
	if s != nil {
		ugu.SetName(*s)
	}
	return ugu
}

// SetDescription sets the "description" field.
func (ugu *UserGroupUpdate) SetDescription(s string) *UserGroupUpdate {
	ugu.mutation.SetDescription(s)
	return ugu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableDescription(s *string) *UserGroupUpdate {
	if s != nil {
		ugu.SetDescription(*s)
	}
	return ugu
}

// ClearDescription clears the value of the "description" field.
func (ugu *UserGroupUpdate) ClearDescription() *UserGroupUpdate {
	ugu.mutation.ClearDescription()
	return ugu
}

// SetOidcScope sets the "oidc_scope" field.
func (ugu *UserGroupUpdate) SetOidcScope(s string) *UserGroupUpdate {
	ugu.mutation.SetOidcScope(s)
	return ugu
}

// SetNillableOidcScope sets the "oidc_scope" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableOidcScope(s *string) *UserGroupUpdate {
	if s != nil {
		ugu.SetOidcScope(*s)
	}
	return ugu
}

// SetCreatedBy sets the "created_by" field.
func (ugu *UserGroupUpdate) SetCreatedBy(s string) *UserGroupUpdate {
	ugu.mutation.SetCreatedBy(s)
	return ugu
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableCreatedBy(s *string) *UserGroupUpdate {
	if s != nil {
		ugu.SetCreatedBy(*s)
	}
	return ugu
}

// SetUpdatedBy sets the "updated_by" field.
func (ugu *UserGroupUpdate) SetUpdatedBy(s string) *UserGroupUpdate {
	ugu.mutation.SetUpdatedBy(s)
	return ugu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableUpdatedBy(s *string) *UserGroupUpdate {
	if s != nil {
		ugu.SetUpdatedBy(*s)
	}
	return ugu
}

// SetUpdatedAt sets the "updated_at" field.
func (ugu *UserGroupUpdate) SetUpdatedAt(t time.Time) *UserGroupUpdate {
	ugu.mutation.SetUpdatedAt(t)
	return ugu
}

// SetDeletedBy sets the "deleted_by" field.
func (ugu *UserGroupUpdate) SetDeletedBy(s string) *UserGroupUpdate {
	ugu.mutation.SetDeletedBy(s)
	return ugu
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableDeletedBy(s *string) *UserGroupUpdate {
	if s != nil {
		ugu.SetDeletedBy(*s)
	}
	return ugu
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (ugu *UserGroupUpdate) ClearDeletedBy() *UserGroupUpdate {
	ugu.mutation.ClearDeletedBy()
	return ugu
}

// SetDeletedAt sets the "deleted_at" field.
func (ugu *UserGroupUpdate) SetDeletedAt(t time.Time) *UserGroupUpdate {
	ugu.mutation.SetDeletedAt(t)
	return ugu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableDeletedAt(t *time.Time) *UserGroupUpdate {
	if t != nil {
		ugu.SetDeletedAt(*t)
	}
	return ugu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ugu *UserGroupUpdate) ClearDeletedAt() *UserGroupUpdate {
	ugu.mutation.ClearDeletedAt()
	return ugu
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (ugu *UserGroupUpdate) AddItemIDs(ids ...uuid.UUID) *UserGroupUpdate {
	ugu.mutation.AddItemIDs(ids...)
	return ugu
}

// AddItems adds the "items" edges to the Item entity.
func (ugu *UserGroupUpdate) AddItems(i ...*Item) *UserGroupUpdate {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ugu.AddItemIDs(ids...)
}

// Mutation returns the UserGroupMutation object of the builder.
func (ugu *UserGroupUpdate) Mutation() *UserGroupMutation {
	return ugu.mutation
}

// ClearItems clears all "items" edges to the Item entity.
func (ugu *UserGroupUpdate) ClearItems() *UserGroupUpdate {
	ugu.mutation.ClearItems()
	return ugu
}

// RemoveItemIDs removes the "items" edge to Item entities by IDs.
func (ugu *UserGroupUpdate) RemoveItemIDs(ids ...uuid.UUID) *UserGroupUpdate {
	ugu.mutation.RemoveItemIDs(ids...)
	return ugu
}

// RemoveItems removes "items" edges to Item entities.
func (ugu *UserGroupUpdate) RemoveItems(i ...*Item) *UserGroupUpdate {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ugu.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ugu *UserGroupUpdate) Save(ctx context.Context) (int, error) {
	ugu.defaults()
	return withHooks(ctx, ugu.sqlSave, ugu.mutation, ugu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ugu *UserGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := ugu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ugu *UserGroupUpdate) Exec(ctx context.Context) error {
	_, err := ugu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ugu *UserGroupUpdate) ExecX(ctx context.Context) {
	if err := ugu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ugu *UserGroupUpdate) defaults() {
	if _, ok := ugu.mutation.UpdatedAt(); !ok {
		v := usergroup.UpdateDefaultUpdatedAt()
		ugu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ugu *UserGroupUpdate) check() error {
	if v, ok := ugu.mutation.Name(); ok {
		if err := usergroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserGroup.name": %w`, err)}
		}
	}
	if v, ok := ugu.mutation.OidcScope(); ok {
		if err := usergroup.OidcScopeValidator(v); err != nil {
			return &ValidationError{Name: "oidc_scope", err: fmt.Errorf(`ent: validator failed for field "UserGroup.oidc_scope": %w`, err)}
		}
	}
	return nil
}

func (ugu *UserGroupUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ugu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergroup.Table, usergroup.Columns, sqlgraph.NewFieldSpec(usergroup.FieldID, field.TypeUUID))
	if ps := ugu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ugu.mutation.Name(); ok {
		_spec.SetField(usergroup.FieldName, field.TypeString, value)
	}
	if value, ok := ugu.mutation.Description(); ok {
		_spec.SetField(usergroup.FieldDescription, field.TypeString, value)
	}
	if ugu.mutation.DescriptionCleared() {
		_spec.ClearField(usergroup.FieldDescription, field.TypeString)
	}
	if value, ok := ugu.mutation.OidcScope(); ok {
		_spec.SetField(usergroup.FieldOidcScope, field.TypeString, value)
	}
	if value, ok := ugu.mutation.CreatedBy(); ok {
		_spec.SetField(usergroup.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := ugu.mutation.UpdatedBy(); ok {
		_spec.SetField(usergroup.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := ugu.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ugu.mutation.DeletedBy(); ok {
		_spec.SetField(usergroup.FieldDeletedBy, field.TypeString, value)
	}
	if ugu.mutation.DeletedByCleared() {
		_spec.ClearField(usergroup.FieldDeletedBy, field.TypeString)
	}
	if value, ok := ugu.mutation.DeletedAt(); ok {
		_spec.SetField(usergroup.FieldDeletedAt, field.TypeTime, value)
	}
	if ugu.mutation.DeletedAtCleared() {
		_spec.ClearField(usergroup.FieldDeletedAt, field.TypeTime)
	}
	if ugu.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usergroup.ItemsTable,
			Columns: []string{usergroup.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ugu.mutation.RemovedItemsIDs(); len(nodes) > 0 && !ugu.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usergroup.ItemsTable,
			Columns: []string{usergroup.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ugu.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usergroup.ItemsTable,
			Columns: []string{usergroup.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ugu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ugu.mutation.done = true
	return n, nil
}

// UserGroupUpdateOne is the builder for updating a single UserGroup entity.
type UserGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserGroupMutation
}

// SetName sets the "name" field.
func (uguo *UserGroupUpdateOne) SetName(s string) *UserGroupUpdateOne {
	uguo.mutation.SetName(s)
	return uguo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableName(s *string) *UserGroupUpdateOne {
	if s != nil {
		uguo.SetName(*s)
	}
	return uguo
}

// SetDescription sets the "description" field.
func (uguo *UserGroupUpdateOne) SetDescription(s string) *UserGroupUpdateOne {
	uguo.mutation.SetDescription(s)
	return uguo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableDescription(s *string) *UserGroupUpdateOne {
	if s != nil {
		uguo.SetDescription(*s)
	}
	return uguo
}

// ClearDescription clears the value of the "description" field.
func (uguo *UserGroupUpdateOne) ClearDescription() *UserGroupUpdateOne {
	uguo.mutation.ClearDescription()
	return uguo
}

// SetOidcScope sets the "oidc_scope" field.
func (uguo *UserGroupUpdateOne) SetOidcScope(s string) *UserGroupUpdateOne {
	uguo.mutation.SetOidcScope(s)
	return uguo
}

// SetNillableOidcScope sets the "oidc_scope" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableOidcScope(s *string) *UserGroupUpdateOne {
	if s != nil {
		uguo.SetOidcScope(*s)
	}
	return uguo
}

// SetCreatedBy sets the "created_by" field.
func (uguo *UserGroupUpdateOne) SetCreatedBy(s string) *UserGroupUpdateOne {
	uguo.mutation.SetCreatedBy(s)
	return uguo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableCreatedBy(s *string) *UserGroupUpdateOne {
	if s != nil {
		uguo.SetCreatedBy(*s)
	}
	return uguo
}

// SetUpdatedBy sets the "updated_by" field.
func (uguo *UserGroupUpdateOne) SetUpdatedBy(s string) *UserGroupUpdateOne {
	uguo.mutation.SetUpdatedBy(s)
	return uguo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableUpdatedBy(s *string) *UserGroupUpdateOne {
	if s != nil {
		uguo.SetUpdatedBy(*s)
	}
	return uguo
}

// SetUpdatedAt sets the "updated_at" field.
func (uguo *UserGroupUpdateOne) SetUpdatedAt(t time.Time) *UserGroupUpdateOne {
	uguo.mutation.SetUpdatedAt(t)
	return uguo
}

// SetDeletedBy sets the "deleted_by" field.
func (uguo *UserGroupUpdateOne) SetDeletedBy(s string) *UserGroupUpdateOne {
	uguo.mutation.SetDeletedBy(s)
	return uguo
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableDeletedBy(s *string) *UserGroupUpdateOne {
	if s != nil {
		uguo.SetDeletedBy(*s)
	}
	return uguo
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (uguo *UserGroupUpdateOne) ClearDeletedBy() *UserGroupUpdateOne {
	uguo.mutation.ClearDeletedBy()
	return uguo
}

// SetDeletedAt sets the "deleted_at" field.
func (uguo *UserGroupUpdateOne) SetDeletedAt(t time.Time) *UserGroupUpdateOne {
	uguo.mutation.SetDeletedAt(t)
	return uguo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableDeletedAt(t *time.Time) *UserGroupUpdateOne {
	if t != nil {
		uguo.SetDeletedAt(*t)
	}
	return uguo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (uguo *UserGroupUpdateOne) ClearDeletedAt() *UserGroupUpdateOne {
	uguo.mutation.ClearDeletedAt()
	return uguo
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (uguo *UserGroupUpdateOne) AddItemIDs(ids ...uuid.UUID) *UserGroupUpdateOne {
	uguo.mutation.AddItemIDs(ids...)
	return uguo
}

// AddItems adds the "items" edges to the Item entity.
func (uguo *UserGroupUpdateOne) AddItems(i ...*Item) *UserGroupUpdateOne {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return uguo.AddItemIDs(ids...)
}

// Mutation returns the UserGroupMutation object of the builder.
func (uguo *UserGroupUpdateOne) Mutation() *UserGroupMutation {
	return uguo.mutation
}

// ClearItems clears all "items" edges to the Item entity.
func (uguo *UserGroupUpdateOne) ClearItems() *UserGroupUpdateOne {
	uguo.mutation.ClearItems()
	return uguo
}

// RemoveItemIDs removes the "items" edge to Item entities by IDs.
func (uguo *UserGroupUpdateOne) RemoveItemIDs(ids ...uuid.UUID) *UserGroupUpdateOne {
	uguo.mutation.RemoveItemIDs(ids...)
	return uguo
}

// RemoveItems removes "items" edges to Item entities.
func (uguo *UserGroupUpdateOne) RemoveItems(i ...*Item) *UserGroupUpdateOne {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return uguo.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the UserGroupUpdate builder.
func (uguo *UserGroupUpdateOne) Where(ps ...predicate.UserGroup) *UserGroupUpdateOne {
	uguo.mutation.Where(ps...)
	return uguo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uguo *UserGroupUpdateOne) Select(field string, fields ...string) *UserGroupUpdateOne {
	uguo.fields = append([]string{field}, fields...)
	return uguo
}

// Save executes the query and returns the updated UserGroup entity.
func (uguo *UserGroupUpdateOne) Save(ctx context.Context) (*UserGroup, error) {
	uguo.defaults()
	return withHooks(ctx, uguo.sqlSave, uguo.mutation, uguo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uguo *UserGroupUpdateOne) SaveX(ctx context.Context) *UserGroup {
	node, err := uguo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uguo *UserGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := uguo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uguo *UserGroupUpdateOne) ExecX(ctx context.Context) {
	if err := uguo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uguo *UserGroupUpdateOne) defaults() {
	if _, ok := uguo.mutation.UpdatedAt(); !ok {
		v := usergroup.UpdateDefaultUpdatedAt()
		uguo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uguo *UserGroupUpdateOne) check() error {
	if v, ok := uguo.mutation.Name(); ok {
		if err := usergroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserGroup.name": %w`, err)}
		}
	}
	if v, ok := uguo.mutation.OidcScope(); ok {
		if err := usergroup.OidcScopeValidator(v); err != nil {
			return &ValidationError{Name: "oidc_scope", err: fmt.Errorf(`ent: validator failed for field "UserGroup.oidc_scope": %w`, err)}
		}
	}
	return nil
}

func (uguo *UserGroupUpdateOne) sqlSave(ctx context.Context) (_node *UserGroup, err error) {
	if err := uguo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergroup.Table, usergroup.Columns, sqlgraph.NewFieldSpec(usergroup.FieldID, field.TypeUUID))
	id, ok := uguo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uguo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usergroup.FieldID)
		for _, f := range fields {
			if !usergroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usergroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uguo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uguo.mutation.Name(); ok {
		_spec.SetField(usergroup.FieldName, field.TypeString, value)
	}
	if value, ok := uguo.mutation.Description(); ok {
		_spec.SetField(usergroup.FieldDescription, field.TypeString, value)
	}
	if uguo.mutation.DescriptionCleared() {
		_spec.ClearField(usergroup.FieldDescription, field.TypeString)
	}
	if value, ok := uguo.mutation.OidcScope(); ok {
		_spec.SetField(usergroup.FieldOidcScope, field.TypeString, value)
	}
	if value, ok := uguo.mutation.CreatedBy(); ok {
		_spec.SetField(usergroup.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := uguo.mutation.UpdatedBy(); ok {
		_spec.SetField(usergroup.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := uguo.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uguo.mutation.DeletedBy(); ok {
		_spec.SetField(usergroup.FieldDeletedBy, field.TypeString, value)
	}
	if uguo.mutation.DeletedByCleared() {
		_spec.ClearField(usergroup.FieldDeletedBy, field.TypeString)
	}
	if value, ok := uguo.mutation.DeletedAt(); ok {
		_spec.SetField(usergroup.FieldDeletedAt, field.TypeTime, value)
	}
	if uguo.mutation.DeletedAtCleared() {
		_spec.ClearField(usergroup.FieldDeletedAt, field.TypeTime)
	}
	if uguo.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usergroup.ItemsTable,
			Columns: []string{usergroup.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uguo.mutation.RemovedItemsIDs(); len(nodes) > 0 && !uguo.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usergroup.ItemsTable,
			Columns: []string{usergroup.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uguo.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usergroup.ItemsTable,
			Columns: []string{usergroup.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserGroup{config: uguo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uguo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uguo.mutation.done = true
	return _node, nil
}
