/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DigInvAssetClass
 */
export interface DigInvAssetClass {
    /**
     * 
     * @type {string}
     * @memberof DigInvAssetClass
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DigInvAssetClass
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DigInvAssetClass
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DigInvAssetClass
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof DigInvAssetClass
     */
    color?: string;
    /**
     * 
     * @type {number}
     * @memberof DigInvAssetClass
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof DigInvAssetClass
     */
    provider?: string;
}

/**
 * Check if a given object implements the DigInvAssetClass interface.
 */
export function instanceOfDigInvAssetClass(value: object): value is DigInvAssetClass {
    return true;
}

export function DigInvAssetClassFromJSON(json: any): DigInvAssetClass {
    return DigInvAssetClassFromJSONTyped(json, false);
}

export function DigInvAssetClassFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigInvAssetClass {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'color': json['color'] == null ? undefined : json['color'],
        'order': json['order'] == null ? undefined : json['order'],
        'provider': json['provider'] == null ? undefined : json['provider'],
    };
}

export function DigInvAssetClassToJSON(json: any): DigInvAssetClass {
    return DigInvAssetClassToJSONTyped(json, false);
}

export function DigInvAssetClassToJSONTyped(value?: DigInvAssetClass | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'icon': value['icon'],
        'color': value['color'],
        'order': value['order'],
        'provider': value['provider'],
    };
}

