/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DigInvItem } from './DigInvItem';
import {
    DigInvItemFromJSON,
    DigInvItemFromJSONTyped,
    DigInvItemToJSON,
    DigInvItemToJSONTyped,
} from './DigInvItem';

/**
 * 
 * @export
 * @interface DigInvItems
 */
export interface DigInvItems {
    /**
     * 
     * @type {Array<DigInvItem>}
     * @memberof DigInvItems
     */
    items?: Array<DigInvItem>;
}

/**
 * Check if a given object implements the DigInvItems interface.
 */
export function instanceOfDigInvItems(value: object): value is DigInvItems {
    return true;
}

export function DigInvItemsFromJSON(json: any): DigInvItems {
    return DigInvItemsFromJSONTyped(json, false);
}

export function DigInvItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigInvItems {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(DigInvItemFromJSON)),
    };
}

export function DigInvItemsToJSON(json: any): DigInvItems {
    return DigInvItemsToJSONTyped(json, false);
}

export function DigInvItemsToJSONTyped(value?: DigInvItems | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(DigInvItemToJSON)),
    };
}

