/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DigInvExchangeCodeMessage
 */
export interface DigInvExchangeCodeMessage {
    /**
     * 
     * @type {string}
     * @memberof DigInvExchangeCodeMessage
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof DigInvExchangeCodeMessage
     */
    state?: string;
}

/**
 * Check if a given object implements the DigInvExchangeCodeMessage interface.
 */
export function instanceOfDigInvExchangeCodeMessage(value: object): value is DigInvExchangeCodeMessage {
    return true;
}

export function DigInvExchangeCodeMessageFromJSON(json: any): DigInvExchangeCodeMessage {
    return DigInvExchangeCodeMessageFromJSONTyped(json, false);
}

export function DigInvExchangeCodeMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigInvExchangeCodeMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'state': json['state'] == null ? undefined : json['state'],
    };
}

export function DigInvExchangeCodeMessageToJSON(json: any): DigInvExchangeCodeMessage {
    return DigInvExchangeCodeMessageToJSONTyped(json, false);
}

export function DigInvExchangeCodeMessageToJSONTyped(value?: DigInvExchangeCodeMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'state': value['state'],
    };
}

