/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DigInvElementId
 */
export interface DigInvElementId {
    /**
     * 
     * @type {string}
     * @memberof DigInvElementId
     */
    id?: string;
}

/**
 * Check if a given object implements the DigInvElementId interface.
 */
export function instanceOfDigInvElementId(value: object): value is DigInvElementId {
    return true;
}

export function DigInvElementIdFromJSON(json: any): DigInvElementId {
    return DigInvElementIdFromJSONTyped(json, false);
}

export function DigInvElementIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigInvElementId {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function DigInvElementIdToJSON(json: any): DigInvElementId {
    return DigInvElementIdToJSONTyped(json, false);
}

export function DigInvElementIdToJSONTyped(value?: DigInvElementId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

