/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DigInvTag } from './DigInvTag';
import {
    DigInvTagFromJSON,
    DigInvTagFromJSONTyped,
    DigInvTagToJSON,
    DigInvTagToJSONTyped,
} from './DigInvTag';

/**
 * 
 * @export
 * @interface DigInvTags
 */
export interface DigInvTags {
    /**
     * 
     * @type {Array<DigInvTag>}
     * @memberof DigInvTags
     */
    tags?: Array<DigInvTag>;
}

/**
 * Check if a given object implements the DigInvTags interface.
 */
export function instanceOfDigInvTags(value: object): value is DigInvTags {
    return true;
}

export function DigInvTagsFromJSON(json: any): DigInvTags {
    return DigInvTagsFromJSONTyped(json, false);
}

export function DigInvTagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigInvTags {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(DigInvTagFromJSON)),
    };
}

export function DigInvTagsToJSON(json: any): DigInvTags {
    return DigInvTagsToJSONTyped(json, false);
}

export function DigInvTagsToJSONTyped(value?: DigInvTags | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(DigInvTagToJSON)),
    };
}

