/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DigInvAssetClass } from './DigInvAssetClass';
import {
    DigInvAssetClassFromJSON,
    DigInvAssetClassFromJSONTyped,
    DigInvAssetClassToJSON,
    DigInvAssetClassToJSONTyped,
} from './DigInvAssetClass';

/**
 * 
 * @export
 * @interface DigInvAssetClasses
 */
export interface DigInvAssetClasses {
    /**
     * 
     * @type {Array<DigInvAssetClass>}
     * @memberof DigInvAssetClasses
     */
    classes?: Array<DigInvAssetClass>;
}

/**
 * Check if a given object implements the DigInvAssetClasses interface.
 */
export function instanceOfDigInvAssetClasses(value: object): value is DigInvAssetClasses {
    return true;
}

export function DigInvAssetClassesFromJSON(json: any): DigInvAssetClasses {
    return DigInvAssetClassesFromJSONTyped(json, false);
}

export function DigInvAssetClassesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigInvAssetClasses {
    if (json == null) {
        return json;
    }
    return {
        
        'classes': json['classes'] == null ? undefined : ((json['classes'] as Array<any>).map(DigInvAssetClassFromJSON)),
    };
}

export function DigInvAssetClassesToJSON(json: any): DigInvAssetClasses {
    return DigInvAssetClassesToJSONTyped(json, false);
}

export function DigInvAssetClassesToJSONTyped(value?: DigInvAssetClasses | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'classes': value['classes'] == null ? undefined : ((value['classes'] as Array<any>).map(DigInvAssetClassToJSON)),
    };
}

