/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DigInvUserInfoMessage
 */
export interface DigInvUserInfoMessage {
    /**
     * 
     * @type {string}
     * @memberof DigInvUserInfoMessage
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof DigInvUserInfoMessage
     */
    email?: string;
}

/**
 * Check if a given object implements the DigInvUserInfoMessage interface.
 */
export function instanceOfDigInvUserInfoMessage(value: object): value is DigInvUserInfoMessage {
    return true;
}

export function DigInvUserInfoMessageFromJSON(json: any): DigInvUserInfoMessage {
    return DigInvUserInfoMessageFromJSONTyped(json, false);
}

export function DigInvUserInfoMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigInvUserInfoMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'subject': json['subject'] == null ? undefined : json['subject'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function DigInvUserInfoMessageToJSON(json: any): DigInvUserInfoMessage {
    return DigInvUserInfoMessageToJSONTyped(json, false);
}

export function DigInvUserInfoMessageToJSONTyped(value?: DigInvUserInfoMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subject': value['subject'],
        'email': value['email'],
    };
}

