/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DigInvItem
 */
export interface DigInvItem {
    /**
     * 
     * @type {string}
     * @memberof DigInvItem
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DigInvItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DigInvItem
     */
    description?: string;
}

/**
 * Check if a given object implements the DigInvItem interface.
 */
export function instanceOfDigInvItem(value: object): value is DigInvItem {
    return true;
}

export function DigInvItemFromJSON(json: any): DigInvItem {
    return DigInvItemFromJSONTyped(json, false);
}

export function DigInvItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigInvItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function DigInvItemToJSON(json: any): DigInvItem {
    return DigInvItemToJSONTyped(json, false);
}

export function DigInvItemToJSONTyped(value?: DigInvItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

