/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DigInvTag
 */
export interface DigInvTag {
    /**
     * 
     * @type {string}
     * @memberof DigInvTag
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DigInvTag
     */
    name?: string;
}

/**
 * Check if a given object implements the DigInvTag interface.
 */
export function instanceOfDigInvTag(value: object): value is DigInvTag {
    return true;
}

export function DigInvTagFromJSON(json: any): DigInvTag {
    return DigInvTagFromJSONTyped(json, false);
}

export function DigInvTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigInvTag {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function DigInvTagToJSON(json: any): DigInvTag {
    return DigInvTagToJSONTyped(json, false);
}

export function DigInvTagToJSONTyped(value?: DigInvTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

