/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DigInvUserGroup
 */
export interface DigInvUserGroup {
    /**
     * 
     * @type {string}
     * @memberof DigInvUserGroup
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DigInvUserGroup
     */
    name?: string;
}

/**
 * Check if a given object implements the DigInvUserGroup interface.
 */
export function instanceOfDigInvUserGroup(value: object): value is DigInvUserGroup {
    return true;
}

export function DigInvUserGroupFromJSON(json: any): DigInvUserGroup {
    return DigInvUserGroupFromJSONTyped(json, false);
}

export function DigInvUserGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigInvUserGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function DigInvUserGroupToJSON(json: any): DigInvUserGroup {
    return DigInvUserGroupToJSONTyped(json, false);
}

export function DigInvUserGroupToJSONTyped(value?: DigInvUserGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

