/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AssetClass
 */
export interface V1AssetClass {
    /**
     * 
     * @type {string}
     * @memberof V1AssetClass
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1AssetClass
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1AssetClass
     */
    description?: string;
}

/**
 * Check if a given object implements the V1AssetClass interface.
 */
export function instanceOfV1AssetClass(value: object): value is V1AssetClass {
    return true;
}

export function V1AssetClassFromJSON(json: any): V1AssetClass {
    return V1AssetClassFromJSONTyped(json, false);
}

export function V1AssetClassFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AssetClass {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function V1AssetClassToJSON(json: any): V1AssetClass {
    return V1AssetClassToJSONTyped(json, false);
}

export function V1AssetClassToJSONTyped(value?: V1AssetClass | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

