/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1AssetClass } from './V1AssetClass';
import {
    V1AssetClassFromJSON,
    V1AssetClassFromJSONTyped,
    V1AssetClassToJSON,
    V1AssetClassToJSONTyped,
} from './V1AssetClass';

/**
 * 
 * @export
 * @interface V1AssetClasses
 */
export interface V1AssetClasses {
    /**
     * 
     * @type {Array<V1AssetClass>}
     * @memberof V1AssetClasses
     */
    classes?: Array<V1AssetClass>;
}

/**
 * Check if a given object implements the V1AssetClasses interface.
 */
export function instanceOfV1AssetClasses(value: object): value is V1AssetClasses {
    return true;
}

export function V1AssetClassesFromJSON(json: any): V1AssetClasses {
    return V1AssetClassesFromJSONTyped(json, false);
}

export function V1AssetClassesFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AssetClasses {
    if (json == null) {
        return json;
    }
    return {
        
        'classes': json['classes'] == null ? undefined : ((json['classes'] as Array<any>).map(V1AssetClassFromJSON)),
    };
}

export function V1AssetClassesToJSON(json: any): V1AssetClasses {
    return V1AssetClassesToJSONTyped(json, false);
}

export function V1AssetClassesToJSONTyped(value?: V1AssetClasses | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'classes': value['classes'] == null ? undefined : ((value['classes'] as Array<any>).map(V1AssetClassToJSON)),
    };
}

