/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ElementId
 */
export interface V1ElementId {
    /**
     * 
     * @type {string}
     * @memberof V1ElementId
     */
    id?: string;
}

/**
 * Check if a given object implements the V1ElementId interface.
 */
export function instanceOfV1ElementId(value: object): value is V1ElementId {
    return true;
}

export function V1ElementIdFromJSON(json: any): V1ElementId {
    return V1ElementIdFromJSONTyped(json, false);
}

export function V1ElementIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ElementId {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function V1ElementIdToJSON(json: any): V1ElementId {
    return V1ElementIdToJSONTyped(json, false);
}

export function V1ElementIdToJSONTyped(value?: V1ElementId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

