/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ExchangeCodeMessage
 */
export interface V1ExchangeCodeMessage {
    /**
     * 
     * @type {string}
     * @memberof V1ExchangeCodeMessage
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ExchangeCodeMessage
     */
    state?: string;
}

/**
 * Check if a given object implements the V1ExchangeCodeMessage interface.
 */
export function instanceOfV1ExchangeCodeMessage(value: object): value is V1ExchangeCodeMessage {
    return true;
}

export function V1ExchangeCodeMessageFromJSON(json: any): V1ExchangeCodeMessage {
    return V1ExchangeCodeMessageFromJSONTyped(json, false);
}

export function V1ExchangeCodeMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ExchangeCodeMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'state': json['state'] == null ? undefined : json['state'],
    };
}

export function V1ExchangeCodeMessageToJSON(json: any): V1ExchangeCodeMessage {
    return V1ExchangeCodeMessageToJSONTyped(json, false);
}

export function V1ExchangeCodeMessageToJSONTyped(value?: V1ExchangeCodeMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'state': value['state'],
    };
}

