/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Group } from './V1Group';
import {
    V1GroupFromJSON,
    V1GroupFromJSONTyped,
    V1GroupToJSON,
    V1GroupToJSONTyped,
} from './V1Group';

/**
 * 
 * @export
 * @interface V1Groups
 */
export interface V1Groups {
    /**
     * 
     * @type {Array<V1Group>}
     * @memberof V1Groups
     */
    groups?: Array<V1Group>;
}

/**
 * Check if a given object implements the V1Groups interface.
 */
export function instanceOfV1Groups(value: object): value is V1Groups {
    return true;
}

export function V1GroupsFromJSON(json: any): V1Groups {
    return V1GroupsFromJSONTyped(json, false);
}

export function V1GroupsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Groups {
    if (json == null) {
        return json;
    }
    return {
        
        'groups': json['groups'] == null ? undefined : ((json['groups'] as Array<any>).map(V1GroupFromJSON)),
    };
}

export function V1GroupsToJSON(json: any): V1Groups {
    return V1GroupsToJSONTyped(json, false);
}

export function V1GroupsToJSONTyped(value?: V1Groups | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groups': value['groups'] == null ? undefined : ((value['groups'] as Array<any>).map(V1GroupToJSON)),
    };
}

