/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1Group
 */
export interface V1Group {
    /**
     * 
     * @type {string}
     * @memberof V1Group
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Group
     */
    name?: string;
}

/**
 * Check if a given object implements the V1Group interface.
 */
export function instanceOfV1Group(value: object): value is V1Group {
    return true;
}

export function V1GroupFromJSON(json: any): V1Group {
    return V1GroupFromJSONTyped(json, false);
}

export function V1GroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Group {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function V1GroupToJSON(json: any): V1Group {
    return V1GroupToJSONTyped(json, false);
}

export function V1GroupToJSONTyped(value?: V1Group | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

