/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Item } from './V1Item';
import {
    V1ItemFromJSON,
    V1ItemFromJSONTyped,
    V1ItemToJSON,
    V1ItemToJSONTyped,
} from './V1Item';

/**
 * 
 * @export
 * @interface V1Items
 */
export interface V1Items {
    /**
     * 
     * @type {Array<V1Item>}
     * @memberof V1Items
     */
    items?: Array<V1Item>;
}

/**
 * Check if a given object implements the V1Items interface.
 */
export function instanceOfV1Items(value: object): value is V1Items {
    return true;
}

export function V1ItemsFromJSON(json: any): V1Items {
    return V1ItemsFromJSONTyped(json, false);
}

export function V1ItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Items {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(V1ItemFromJSON)),
    };
}

export function V1ItemsToJSON(json: any): V1Items {
    return V1ItemsToJSONTyped(json, false);
}

export function V1ItemsToJSONTyped(value?: V1Items | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(V1ItemToJSON)),
    };
}

