/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ItemId
 */
export interface V1ItemId {
    /**
     * 
     * @type {string}
     * @memberof V1ItemId
     */
    id?: string;
}

/**
 * Check if a given object implements the V1ItemId interface.
 */
export function instanceOfV1ItemId(value: object): value is V1ItemId {
    return true;
}

export function V1ItemIdFromJSON(json: any): V1ItemId {
    return V1ItemIdFromJSONTyped(json, false);
}

export function V1ItemIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ItemId {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function V1ItemIdToJSON(json: any): V1ItemId {
    return V1ItemIdToJSONTyped(json, false);
}

export function V1ItemIdToJSONTyped(value?: V1ItemId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

