/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1StringMessage
 */
export interface V1StringMessage {
    /**
     * 
     * @type {string}
     * @memberof V1StringMessage
     */
    value?: string;
}

/**
 * Check if a given object implements the V1StringMessage interface.
 */
export function instanceOfV1StringMessage(value: object): value is V1StringMessage {
    return true;
}

export function V1StringMessageFromJSON(json: any): V1StringMessage {
    return V1StringMessageFromJSONTyped(json, false);
}

export function V1StringMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1StringMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function V1StringMessageToJSON(json: any): V1StringMessage {
    return V1StringMessageToJSONTyped(json, false);
}

export function V1StringMessageToJSONTyped(value?: V1StringMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

