/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1Tag
 */
export interface V1Tag {
    /**
     * 
     * @type {string}
     * @memberof V1Tag
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Tag
     */
    name?: string;
}

/**
 * Check if a given object implements the V1Tag interface.
 */
export function instanceOfV1Tag(value: object): value is V1Tag {
    return true;
}

export function V1TagFromJSON(json: any): V1Tag {
    return V1TagFromJSONTyped(json, false);
}

export function V1TagFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Tag {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function V1TagToJSON(json: any): V1Tag {
    return V1TagToJSONTyped(json, false);
}

export function V1TagToJSONTyped(value?: V1Tag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

