/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1TagId
 */
export interface V1TagId {
    /**
     * 
     * @type {string}
     * @memberof V1TagId
     */
    id?: string;
}

/**
 * Check if a given object implements the V1TagId interface.
 */
export function instanceOfV1TagId(value: object): value is V1TagId {
    return true;
}

export function V1TagIdFromJSON(json: any): V1TagId {
    return V1TagIdFromJSONTyped(json, false);
}

export function V1TagIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TagId {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function V1TagIdToJSON(json: any): V1TagId {
    return V1TagIdToJSONTyped(json, false);
}

export function V1TagIdToJSONTyped(value?: V1TagId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

