/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Tag } from './V1Tag';
import {
    V1TagFromJSON,
    V1TagFromJSONTyped,
    V1TagToJSON,
    V1TagToJSONTyped,
} from './V1Tag';

/**
 * 
 * @export
 * @interface V1Tags
 */
export interface V1Tags {
    /**
     * 
     * @type {Array<V1Tag>}
     * @memberof V1Tags
     */
    tags?: Array<V1Tag>;
}

/**
 * Check if a given object implements the V1Tags interface.
 */
export function instanceOfV1Tags(value: object): value is V1Tags {
    return true;
}

export function V1TagsFromJSON(json: any): V1Tags {
    return V1TagsFromJSONTyped(json, false);
}

export function V1TagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Tags {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(V1TagFromJSON)),
    };
}

export function V1TagsToJSON(json: any): V1Tags {
    return V1TagsToJSONTyped(json, false);
}

export function V1TagsToJSONTyped(value?: V1Tags | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(V1TagToJSON)),
    };
}

