/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1UserGroup
 */
export interface V1UserGroup {
    /**
     * 
     * @type {string}
     * @memberof V1UserGroup
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UserGroup
     */
    name?: string;
}

/**
 * Check if a given object implements the V1UserGroup interface.
 */
export function instanceOfV1UserGroup(value: object): value is V1UserGroup {
    return true;
}

export function V1UserGroupFromJSON(json: any): V1UserGroup {
    return V1UserGroupFromJSONTyped(json, false);
}

export function V1UserGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UserGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function V1UserGroupToJSON(json: any): V1UserGroup {
    return V1UserGroupToJSONTyped(json, false);
}

export function V1UserGroupToJSONTyped(value?: V1UserGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

