/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1UserInfoMessage
 */
export interface V1UserInfoMessage {
    /**
     * 
     * @type {string}
     * @memberof V1UserInfoMessage
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UserInfoMessage
     */
    email?: string;
}

/**
 * Check if a given object implements the V1UserInfoMessage interface.
 */
export function instanceOfV1UserInfoMessage(value: object): value is V1UserInfoMessage {
    return true;
}

export function V1UserInfoMessageFromJSON(json: any): V1UserInfoMessage {
    return V1UserInfoMessageFromJSONTyped(json, false);
}

export function V1UserInfoMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UserInfoMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'subject': json['subject'] == null ? undefined : json['subject'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function V1UserInfoMessageToJSON(json: any): V1UserInfoMessage {
    return V1UserInfoMessageToJSONTyped(json, false);
}

export function V1UserInfoMessageToJSONTyped(value?: V1UserInfoMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subject': value['subject'],
        'email': value['email'],
    };
}

