/* tslint:disable */
/* eslint-disable */
/**
 * backend.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1UserSubjectMessage
 */
export interface V1UserSubjectMessage {
    /**
     * 
     * @type {string}
     * @memberof V1UserSubjectMessage
     */
    subject?: string;
}

/**
 * Check if a given object implements the V1UserSubjectMessage interface.
 */
export function instanceOfV1UserSubjectMessage(value: object): value is V1UserSubjectMessage {
    return true;
}

export function V1UserSubjectMessageFromJSON(json: any): V1UserSubjectMessage {
    return V1UserSubjectMessageFromJSONTyped(json, false);
}

export function V1UserSubjectMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UserSubjectMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'subject': json['subject'] == null ? undefined : json['subject'],
    };
}

export function V1UserSubjectMessageToJSON(json: any): V1UserSubjectMessage {
    return V1UserSubjectMessageToJSONTyped(json, false);
}

export function V1UserSubjectMessageToJSONTyped(value?: V1UserSubjectMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subject': value['subject'],
    };
}

